openapi: 3.0.0
info:
  title: connexion sample
  description: OpenAPI and connexion sample
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: sample
paths:
  /hoge:
    get:
      operationId: hoge.get_sample
      summary: hoge sample
      description: hoge get sample
      responses:
        '200':
          description: getのサンプル
          content:
            application/json:
              schema:
                type: string
                example: "hello hoge sample!!"
tags:
  - name: hoge
    description: サンプルAPIです。